version: '3'

services:
  # 애플리케이션 서비스
  service:
    container_name: service-server
    image: sunwupark/calmvas
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/calmvas_dev?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - database
    networks:
      - test_network

  database:
    container_name: database
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: calmvas_dev
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql-init.d:/docker-entrypoint-initdb.d
    command:
      - mysqld
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network
  # Prometheus 모니터링 서비스
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    volumes:
#      - ./prometheus.yml:/prometheus/prometheus.yml:ro
#    ports:
#      - "19090:9090"
#    command:
#      - "--web.enable-lifecycle"
#    restart: always
#    networks:
#      - test_network
#    user: root
#
#  # Grafana 모니터링 시각화 서비스
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    volumes:
#      - ./grafana-volume:/var/lib/grafana
#    restart: always
#    networks:
#      - test_network
#    ports:
#      - "13030:3000"
#    user: root

networks:
  test_network:
